import re
from urllib.parse import urljoin
from models import MerchantProduct
from normalize import clean_text, parse_price, normalize_stock
from base import BaseScraper


class GACDScraper(BaseScraper):
    merchant = "GACD"
    base_url = "https://www.gacd.fr"

   def discover_product_urls(self):
    """URLs de test réelles GACD pour valider le scraper."""
    return [
        "https://www.gacd.fr/tooth-mousse-tubes-10-chapeau.html",
        "https://www.gacd.fr/tub-a-materiaux-chapeau.html",
    ]
    @staticmethod
    def _looks_product(url: str) -> bool:
        blocked = ("/centre-aide/", "/qui-sommes-nous/", "/catalogsearch/", "/customer/", "/checkout/")
        return url.startswith("https://www.gacd.fr/") and url.endswith((".html", ".htm")) and not any(x in url for x in blocked)

    def parse_product(self, url: str, html: str):
        soup = self.soup(html)
        title = clean_text((soup.find("h1") or {}).get_text(" ", strip=True) if soup.find("h1") else "")
        page_text = clean_text(soup.get_text(" ", strip=True))

        brand = None
        # GACD visually places manufacturer immediately near the H1; also try JSON-LD brand.
        for obj in self.json_ld(soup):
            if obj.get("@type") == "Product":
                b = obj.get("brand")
                if isinstance(b, dict): brand = b.get("name")
                elif isinstance(b, str): brand = b
                if not title: title = clean_text(obj.get("name"))

        # Each variant is the actual comparable SKU. GACD page text exposes rows containing
        # 'Réf. GACD', 'Réf. Fabricant', stock and price. DOM classes can change, so parse
        # candidate blocks first and fall back to whole-page regex for single-SKU pages.
        products = []
        blocks = soup.select("tr, .product-item, .variant, [class*='variant'], [class*='swatch']")
        for block in blocks:
            txt = clean_text(block.get_text(" ", strip=True))
            if "Réf" not in txt or "Fabricant" not in txt:
                continue
            gacd = re.search(r"Réf\.?\s*GACD\s*:?\s*([A-Z0-9-]+)", txt, re.I)
            mref = re.search(r"Réf\.?\s*Fabricant\s*:?\s*([^\s€]+)", txt, re.I)
            if not (gacd or mref):
                continue
            price_matches = re.findall(r"\d[\d\s\u202f]*(?:,\d{1,2})?\s*€", txt)
            price = parse_price(price_matches[0]) if price_matches else None
            stock_match = re.search(r"(En stock|Sur commande|En réapprovisionnement|Arrêté)", txt, re.I)
            # Strip metadata from variant label.
            name = re.sub(r"Réf\..*$", "", txt, flags=re.I).strip() or title
            products.append(MerchantProduct(
                merchant=self.merchant, url=url, name=name,
                merchant_reference=gacd.group(1) if gacd else None,
                manufacturer_reference=mref.group(1) if mref else None,
                brand=brand, price=price,
                availability=normalize_stock(stock_match.group(1) if stock_match else None),
            ))

        if products:
            # Remove duplicate blocks generated by responsive markup.
            unique = {}
            for p in products:
                key = (p.merchant_reference, p.manufacturer_reference, p.name)
                unique[key] = p
            return list(unique.values())

        gacd = re.search(r"Référence\s+GACD\s*:?\s*([A-Z0-9-]+)", page_text, re.I)
        mref = re.search(r"Référence\s+fabricant\s*:?\s*([^\s€]+)", page_text, re.I)
        price = parse_price(page_text[page_text.find("€")-25:page_text.find("€")+1]) if "€" in page_text else None
        return [MerchantProduct(
            merchant=self.merchant, url=url, name=title, price=price,
            merchant_reference=gacd.group(1) if gacd else None,
            manufacturer_reference=mref.group(1) if mref else None,
            brand=brand,
        )]
